### ISSUE TITLE
pyamf don't work with python 2.7.6 (ubuntu 14.04)

### ISSUE THREAD

**Issue by djeps** [hydralabs/pyamf#26]
there is content_type and httplib problems, the first was solved withing ./remoting/client/__init__.py, and the latter with python libs duplication and hacking (urllib2 and httplib).

Is anyone aware of that? Recently I had to work with amf3 and had a tough time figuring all out. I'll be happy to help test and try to solve all issues in pyamf if there is room for that.

**Comment by njoyce** [comment]
Can you post the patch that you applied and I can take a deeper look. There is some pretty decent test coverage for the remoting client and the tests are currently passing for python 2.7 on Travis (https://travis-ci.org/hydralabs/pyamf/jobs/47837047).

**Comment by njoyce** [comment]
Travis CI is still on Precise - http://docs.travis-ci.com/user/ci-environment/#CI-environment-OS I don't have access to Trusty. Without further info, I can't diagnose further (even a simple stacktrace would be useful).

Closing until OP responds.
