### ISSUE TITLE
New release soon

### ISSUE THREAD

**Issue by frewsxcv** [hydralabs/pyamf#42]
Lots of great changes have been committed recently. Would love to be able to use the from PyPi

**Comment by njoyce** [comment]
Will do - still have a few changes I need to make and then some real world testing. Will release 0.7 hopefully sometime next week.

**Comment by frewsxcv** [comment]
If there's anything I can do/work on to speed this up, let me know, would love to help :)

**Comment by njoyce** [comment]
I want to land the new google appengine ndb adapter (which will close #30) and then we can start the release process - should only be a couple of days.

Would it be possible to try the new version out in your project (perhaps in a dev/staging environment)?

**Comment by frewsxcv** [comment]
I just tried this locally and things seem to work

**Comment by njoyce** [comment]
FYI - I am working on ensuring that this new version of PyAMF works for a large legacy code base. Once that is complete I will tag 0.7

**Comment by frewsxcv** [comment]
@njoyce Awesome! Thanks for your hard work

**Comment by njoyce** [comment]
https://pypi.python.org/pypi/PyAMF
