### ISSUE TITLE
pyamf pyramid_rpc 0.5.2 tests fail with PyAMF 0.7.2

### ISSUE THREAD

**Issue by frispete** [hydralabs/pyamf#56]
Hi,

I'm preparing some python packages for the official openSUSE distribution on public build service.The pyramid_rpc build fails due to PyAMF IOErrors::

usr/lib/python2.7/site-packages/nose/config.py:435: DeprecationWarning: Use of multiple -w arguments is deprecated and support may be removed in a future release. You can get the same behavior by passing directories without the -w argument on the command line, or by using the --tests argument in a configuration file.

[  101s]   DeprecationWarning)
[  101s] ...F......E.........................................................................................
[  101s] ======================================================================
[  101s] ERROR: test_unknown_request (pyramid_rpc.tests.test_amfgateway.TestAmfViewGateway)
[  101s] ----------------------------------------------------------------------
[  101s] Traceback (most recent call last):
[  101s]   File "/home/abuild/rpmbuild/BUILD/pyramid_rpc-0.6.1/pyramid_rpc/tests/test_amfgateway.py", line 58, in test_unknown_request
[  101s]     envelope = remoting.decode(response.body)
[  101s]   File "/usr/lib64/python2.7/site-packages/pyamf/remoting/__init__.py", line 611, in decode
[  101s]     msg.amfVersion = stream.read_ushort()
[  101s]   File "cpyamf/util.pyx", line 576, in cpyamf.util.cBufferedByteStream.read_ushort (cpyamf/util.c:5997)
[  101s]   File "cpyamf/util.pyx", line 582, in cpyamf.util.cBufferedByteStream.read_ushort (cpyamf/util.c:5940)
[  101s]   File "cpyamf/util.pyx", line 459, in cpyamf.util.cBufferedByteStream.unpack_int (cpyamf/util.c:4796)
[  101s] IOError
[  101s] 
[  101s] ======================================================================
[  101s] FAIL: test_expected_exception_encode (pyramid_rpc.tests.test_amfgateway.TestAmfViewGateway)
[  101s] ----------------------------------------------------------------------
[  101s] Traceback (most recent call last):
[  101s]   File "/home/abuild/rpmbuild/BUILD/pyramid_rpc-0.6.1/pyramid_rpc/tests/test_amfgateway.py", line 129, in test_expected_exception_encode
[  101s]     assert 'unable to be encoded' in response.detail
[  101s] AssertionError

see:
https://build.opensuse.org/package/live_build_log/home:frispete:python/python-pyramid_rpc/openSUSE_13.2/x86_64

Question is, which tree to bark at ;) 
It smells like this project. Hmm.

**Comment by frispete** [comment]
Guys, any interest to get current PyAMF going with pyramid_rpc module?

Its maintainer tried to get it going with current PyAMF code, as well as I did, but PyAMF makes it really hard for the non enlighted to wrap one's mind around it.  The maintainer gave up, and limited the PyAMF version to >= 0.6.99: https://github.com/Pylons/pyramid_rpc/blob/master/setup.py#L81

Now I tried to get a 0.6.2 version building - but failed. The setuptools fiddling was fixable easily, but the pyx code isn't compatible with todays Cython anymore:

 [    7s] cythoning cpyamf/amf0.pyx to cpyamf/amf0.c
[    7s] 
[    7s] Error compiling Cython file:
[    7s] ------------------------------------------------------------
[    7s] ...
[    7s] 
[    7s] 
[    7s] cdef class Context(codec.Context):
[    7s]     cdef amf3.Context amf3_context
[    7s] 
[    7s]     cpdef int clear(self) except -1:
[    7s]          ^
[    7s] ------------------------------------------------------------
[    7s] 
[    7s] cpyamf/amf0.pyx:50:10: Signature not compatible with previous declaration
[    7s] 
[    7s] Error compiling Cython file:
[    7s] ------------------------------------------------------------
[    7s] ...
[    7s]     cdef IndexedCollection objects
[    7s]     cdef dict unicodes
[    7s]     cdef dict _strings
[    7s]     cdef public dict extra
[    7s] 
[    7s]     cpdef int clear(self) except? -1
[    7s]                   ^
[    7s] ------------------------------------------------------------
[    7s] 
[    7s] cpyamf/codec.pxd:43:19: Previous declaration is here
[    7s] 
[    7s] Error compiling Cython file:
[    7s] ------------------------------------------------------------
[    7s] ...
[    7s]     cdef int writeNumber(self, n) except -1:
[    7s]         self.writeType(TYPE_NUMBER)
[    7s] 
[    7s]         return self.stream.write_double(n)
[    7s] 
[    7s]     cdef int writeLong(self, object a):
[    7s]         ^
[    7s] ------------------------------------------------------------
[    7s] 
[    7s] cpyamf/amf0.pyx:406:9: Signature not compatible with previous declaration
[    7s] 
[    7s] Error compiling Cython file:
[    7s] ------------------------------------------------------------
[    7s] ...
[    7s]     cdef int writeUndefined(self, object o) except -1
[    7s]     cdef int writeString(self, object o) except -1
[    7s]     cdef int writeBytes(self, object o) except -1
[    7s]     cdef int writeBoolean(self, object o) except -1
[    7s]     cdef int writeInt(self, object o) except -1
[    7s]     cdef int writeLong(self, object o) except -1
[    7s]                      ^
[    7s] ------------------------------------------------------------
[    7s] 
[    7s] cpyamf/codec.pxd:97:22: Previous declaration is here
[...]

Another dead end.

The only remaining option is disabling/removing PyAMF support from pyramid_rpc, if nobody from the PyAMF camp stands up and give it a little love to the _now_ broken code. It should be easily fixable with enough insight. Give it a go, please.

Broken build logs are still available here:
https://build.opensuse.org/package/show/home:frispete:python/python-pyramid_rpc

pyramid_rpc is hosted here:
https://github.com/Pylons/pyramid_rpc

**Comment by njoyce** [comment]
Hi - definitely interested in getting this fixed up - will take a look this weekend.

**Comment by frispete** [comment]
Hi Nick,

On Mittwoch, 5. August 2015 22:10:44 Nick Joyce wrote:
> Hi - definitely interested in getting this fixed up - will take a look this
> weekend.

Okay, I restored the PyAMF package in my repository now (I removed it already 
as I had no hope in getting any feedback from your project..). 

Therefor the links documenting the failures should be valid again in a couple 
of minutes, but the timestamps will not. If you need more infos, let me know.

Pete

**Comment by njoyce** [comment]
This was not an issue with PyAMF - see https://github.com/Pylons/pyramid_rpc/pull/43 for more details.
