### ISSUE TITLE
Where is the documentation?

### ISSUE THREAD

**Issue by anacelto** [hydralabs/pyamf#65]
Hi,

Where we can find a good documentation for this library? Because pyamf.org is hacked...

Regards

**Comment by njoyce** [comment]
Hi - Check out https://py-amf.org.

The domain lapsed and they jumped on it :/

I need to get the references updated in the documentation.

**Comment by anacelto** [comment]
Hi Njoyce, thanks for your fas answer. What about api.pyamf.org? because py-amf.org library reference links to api.pyamf.org but not work... do u have an alternative?

thanks!!

**Comment by anacelto** [comment]
Hi again,

I'm testing with pyamf. But I'm unable to decode an AMF hex string. I have that hex: 030003666f6f0200036261720000 

Decoded is something like { foo: bar }

How I can decode it with pyamf?

Thanks!
