### ISSUE TITLE
Unable to decode custom Flex objects

### ISSUE THREAD

**Issue by mejmo** [hydralabs/pyamf#66]
Hello guys,

how can I specify my custom decoder. I am connecting to the Flex server which I cannot control, it sends some simple objects (actually list of objects) in response body, however decoder throws exception:

```
Exception TypeError: 'list indices must be integers, not str' in 'cpyamf.amf0.Decoder.readObjectAttributes' ignored
```

Is there any possibility to get this working?

**Comment by mejmo** [comment]
Pull request and version set up to amf3 did the thing.

**Comment by thijstriemstra** [comment]
what pull request?

**Comment by mejmo** [comment]
https://github.com/hydralabs/pyamf/pull/63

maybe it was just the version change, which I did AFTER this update...
